Fix SSL tests for Python 3.13
SSL tests fail with Python 3.13 (NetBox v4.6).
```
FAILED tests/test_netbox_kea_api_server.py::test_server_create_basic_auth - pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'dhcp6_url': ['Unable to get DHCPv6 version: SSLError(MaxRetryError("HTTPSConnectionPool(host=\'kea-dhcp6\', port=8003): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: Basic Constraints of CA cert not marked critical (_ssl.c:1081)\')))"))']}
```
```
FAILED tests/test_netbox_kea_api_server.py::test_server_create_basic_auth - pynetbox.core.query.RequestError: The request failed with code 400 Bad Request: {'dhcp6_url': ['Unable to get DHCPv6 version: SSLError(MaxRetryError("HTTPSConnectionPool(host=\'kea-dhcp6\', port=8003): Max retries exceeded with url: / (Caused by SSLError(SSLCertVerificationError(1, \'[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: CA cert does not include key usage extension (_ssl.c:1081)\')))"))']}
```

Mark basic constraints as critical and add `keyUsage`.